project:
  type: book

book:
  title: "It is easy to use the NEX-GDDP-CMIP6 data!"
  author: "Valerio Pascucci,  Luis Sanchez, Giorgio Scorzelli,
  Aashish Panta, and Arleth Salinas"
  date: "7/20/2024"
  cover-image: NASA_data.png
  chapters:
    - 000_index.qmd
    - 001_intro.qmd
    - 002_examples.qmd
    - 003_read_different_varibles.qmd
    - 004_compute_temperature_trend.qmd
    - 999_references.qmd

bibliography: references.bib

format:
  html:
    cover-image: NASA_data.png
    theme: cosmo
    toc: true
    toc-depth: 5
  pdf:
    documentclass: scrreprt
    cover-image: NASA_data.png


execute:
  echo: false
jupyter: python3
